MovieApp/ViewModels/NewCustomerViewModel.cs
using MovieApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MovieApp.ViewModels
{
    public class CustomerFormViewModel
    {
        public IEnumerable<MembershipType> MembershipTypes { get; set; }
        public Customer Customer { get; set; }
    }
}

MovieApp/ViewModels/NewMovieViewModel.cs
using MovieApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MovieApp.ViewModels
{
    public class NewMovieViewModel
    {
        public IEnumerable<Genre> Genres { get; set; }
        public Movie Movie { get; set; }
    }
}

MovieApp/Controllers/RentalsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MovieApp.Controllers
{
    public class RentalsController : Controller
    {
        // GET: Rentals
        public ActionResult Index()
        {
            return View();
        }
    }
}

MovieApp/Controllers/api/CustomersController.cs
using AutoMapper;
using MovieApp.Dtos;
using MovieApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Data.Entity;

namespace MovieApp.Controllers.api
{
    public class CustomersController : ApiController
    {
        private ApplicationDbContext _context;
        public CustomersController()
        {
            _context = new ApplicationDbContext();
        }
        //GET /api/customers
        public IHttpActionResult GetCustomers(string query = null)
        {
            var customerDtos = _context.Customers
                .ToList().Select(Mapper.Map<Customer, CustomerDto>);
            
            return Ok(customerDtos);
        }

        //GET /api/customers/id
        public IHttpActionResult GetCustomer(int id)
        {
            var customer = _context.Customers.SingleOrDefault(c => c.Id == id);
            if (customer == null)
                return NotFound();
            return Ok(Mapper.Map<Customer,CustomerDto>(customer));

        }

        //POST /api/customer
    /*    [HttpPost]
        public IHttpActionResult CreateCustomer(CustomerDto customerDto)
        {
            if (!ModelState.IsValid)
                return BadRequest();
            var customer = Mapper.Map<CustomerDto, Customer>(customerDto);
            _context.Customers.Add(customer);
            _context.SaveChanges();
            customerDto.Id = customer.Id;
            return Created(new Uri(Request.RequestUri+ "/" + customer.Id),customerDto);
        }
        */
        //PUT /api/customers/1
        [HttpPut]
        public void UpdateCustomer(int id, CustomerDto customerDto)
        {
            if (!ModelState.IsValid)
                throw new HttpResponseException(HttpStatusCode.BadRequest);
            var customerInDb = _context.Customers.SingleOrDefault(c => c.Id == id);
            if (customerInDb == null)
                throw new HttpResponseException(HttpStatusCode.NotFound);
            Mapper.Map(customerDto, customerInDb);        
            _context.SaveChanges();
        }

        //DELETE /api/customers/1
        [HttpDelete]
        public void DeleteCustomer(int id)
        {
            var customerInDb = _context.Customers.SingleOrDefault(c => c.Id == id);
            if (customerInDb == null)
                throw new HttpResponseException(HttpStatusCode.NotFound);
            _context.Customers.Remove(customerInDb);
            _context.SaveChanges();
        }
    }
}

MovieApp/Controllers/api/MoviesController.cs
using AutoMapper;
using MovieApp.Dtos;
using MovieApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Data.Entity;

namespace MovieApp.Controllers.api
{
    public class MoviesController : ApiController
    {
        ApplicationDbContext _context;
        public MoviesController()
        {
            _context = new ApplicationDbContext();
        }

        //GET /api/movies
        public IHttpActionResult GetMovies(string query = null)
        {
            var moviesQuery = _context.Movies
                .Include(m => m.Genre)
                .Where(m=>m.NumberAvailable > 0);

            if (!String.IsNullOrWhiteSpace(query))
                moviesQuery = moviesQuery.Where(c => c.Name.Contains(query));

            var movieDtos = moviesQuery
                .ToList()
                .Select(Mapper.Map<Movie, MovieDto>);
            return Ok(movieDtos);
        }

        //GET /api/movies/1
        public IHttpActionResult GetMovie(int id)
        {
            var movie = _context.Movies.SingleOrDefault(m => m.Id == id);
            if (movie == null)
                return NotFound();
            return Ok(Mapper.Map<Movie,MovieDto>(movie));
        }

        //POST /api/movies
        [HttpPost]
        public IHttpActionResult CreateMovie(MovieDto movieDto)
        {
            if (!ModelState.IsValid)
                return BadRequest();
            var movie = Mapper.Map<MovieDto, Movie>(movieDto);
            _context.Movies.Add(movie);
            _context.SaveChanges();
            movieDto.Id = movie.Id;
            return Created(new Uri(Request.RequestUri + "/" + movie.Id), movieDto);
        }

        //PUT /api/movies/1
        [HttpPut]
        public void UpdateMovie(int id, MovieDto movieDto)
        {
            if (!ModelState.IsValid)
                throw new HttpResponseException(HttpStatusCode.BadRequest);
            var movieInDb = _context.Movies.SingleOrDefault(m => m.Id == id);
            if (movieInDb == null)
                throw new HttpResponseException(HttpStatusCode.NotFound);
            Mapper.Map(movieDto, movieInDb);
            _context.SaveChanges();
        }

        //DELETE /api/movies/1
        [HttpDelete]
        public void DeleteMovie(int id)
        {
            var movieInDb = _context.Movies.SingleOrDefault(m => m.Id == id);
            if (movieInDb == null)
                throw new HttpResponseException(HttpStatusCode.NotFound);
            _context.Movies.Remove(movieInDb);
            _context.SaveChanges();
        }
    }
}

MovieApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @Html.Partial("_Navbar")
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/lib")
    @RenderSection("scripts", required: false)
</body>
</html>

MovieApp/Views/Shared/_Navbar.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Vidly", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("New Rental", "Index", "Rentals")</li>
                <li>@Html.ActionLink("Customer", "Index", "Customers")</li>
                <li>@Html.ActionLink("Movie", "Index", "Movies")</li>
            </ul>
        </div>
    </div>
</div>

MovieApp/Views/Shared/_NewCustomer.cshtml
@model MovieApp.Models.Customer

@{
    ViewBag.Title = "_NewCustomer";
}
<div class="modal" id="newCustomer" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content" id="myContent">
            <div class="modal-header modalHeader">
                <button type="button" class="close closed" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">New Customer</h4>
            </div>
            <div class="modal-body modalBody" id="divModalBody">
                <form id="form">
                    @Html.AntiForgeryToken()
                    <div class="form-group">
                        @Html.LabelFor(m => m.Name)
                        @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Name)
                    </div>
                    
                    <div class="form-group">
                        @Html.LabelFor(m => m.Birthday)
                        @Html.TextBoxFor(m => m.Birthday, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Birthday)
                    </div>

                    @Html.HiddenFor(m => m.Id)
                </form>
            </div>
            <div class="modal-footer" id="modalFooter">
                <button class="btn btn-success btn-md" type="submit" id="save" onclick="save()"><i class="glyphicon glyphicon-check"></i>Save</button>
                <button type="button" class="btn btn-danger closed" data-dismiss="modal" onclick="close()"><i class="glyphicon glyphicon-remove"></i> Close</button>
            </div>
        </div>
    </div>
</div>

@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        
    </script>
}

MovieApp/Views/Shared/_NewMovie.cshtml
@model MovieApp.ViewModels.NewMovieViewModel
@{
    ViewBag.Title = "_NewMovie";
}
<div class="modal" id="newMovie" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content" id="myContent">
            <div class="modal-header modalHeader">
                <button type="button" class="close closed" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">New Movie</h4>
            </div>
            <div class="modal-body modalBody" id="divModalBody">
                <form id="form">
                    @Html.AntiForgeryToken()
                    <div class="form-group">
                        @Html.LabelFor(m => m.Movie.Name)
                        @Html.TextBoxFor(m => m.Movie.Name, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Movie.Name)
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.Movie.ReleaseDate)
                        @Html.TextBoxFor(m => m.Movie.ReleaseDate, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Movie.ReleaseDate)
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.Movie.DateAdded)
                        @Html.TextBoxFor(m => m.Movie.DateAdded, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Movie.DateAdded)
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.Movie.GenreId)
                        @Html.DropDownListFor(m => m.Movie.GenreId, new SelectList(Model.Genres, "Id", "Name"), "Select Genre", new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Movie.GenreId)
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.Movie.NumberInStock)
                        @Html.TextBoxFor(m => m.Movie.NumberInStock, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Movie.NumberInStock)
                    </div>
                    @Html.HiddenFor(m => m.Movie.Id)
                </form>
            </div>
            <div class="modal-footer" id="modalFooter">
                <button class="btn btn-success btn-md" type="submit" id="save" onclick="save()"><i class="glyphicon glyphicon-check"></i>Save</button>
                <button type="button" class="btn btn-danger closed" data-dismiss="modal"><i class="glyphicon glyphicon-remove"></i> Close</button>
            </div>
        </div>
    </div>
</div>
@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")
}